### PR TITLE
BUGFIX: Update fastapi, starlette and uvicorn packages

### PR DESCRIPTION
**Pull request by diversemix**
Bug found in production - see discussion on slack here: https://climate-policy-radar.slack.com/archives/C04CR0B3KD4/p1674724615493809?thread_ts=1674718871.901429&cid=C04CR0B3KD4

### Discussions on this topic:
- https://stackoverflow.com/a/72677699
- https://github.com/encode/starlette/discussions/1527#discussioncomment-2234702

This can be fixed updating to the latest versions of:
- https://github.com/tiangolo/fastapi
- https://github.com/encode/uvicorn
- https://github.com/encode/starlette

### CODE REVIEW

**Review by THOR300 — APPROVED** [review]
What was fiddly - reproducing the error?

**Comment by diversemix** [comment]
No dealing with getting all the versions compatible :)

**Comment by diversemix** [comment]
Hmmm ... why are there no tests for this PR? Merge GA is here: https://github.com/climatepolicyradar/navigator-backend/actions/runs/4013993683

**Comment by THOR300** [comment]
> No dealing with getting all the versions compatible :)

Interesting, so was poetry failing to resolve deps?

**Pull request merged**
